# ================================
# Spring
spring:
  config:
    activate:
      on-profile: "local"
  # --------------
  # DB
  datasource:
    # JDBC with log4j
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/jonastalk
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ENC(Inj6f4uWRyNr64LV+wP+v6ATYWi9Fx2T)
    password: ENC(rbehroO9rtReft7xWi8Pjw==)
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  # --------------
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
    client-name: jonastalk-auth-api
    netty-threads: 10
    idle-connection-timeout: 10000
    connect-timeout: 10000
    timeout: 3000
    retry-attempts: 3
    retry-interval: 1500
    subscriptions-per-connection: 5
    subscription-connection-minimum-idle-size: 1
    subscription-connection-pool-size: 50
    connection-minimum-idle-size: 10
    connection-pool-size: 100
    database: 0
    dns-monitoring-interval: 5000
    keep-alive: true
    thread-cnt: 30
    lock:
      get: false
      put: true
      wait-sec: 10
      lease-sec: 30

  
  
# ================================ 
# Log
logging:
  level:
    com:
      jonasweet:
        web: DEBUG
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: OFF  # Log SQL Result Data Table
      sqlonly: OFF    # Log SQL
      sqltiming: INFO    # SQL, Time
      connection : OFF  # Connection check